# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_pendingrequests_deleted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSoftDelete',
        ),
    ]
