# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190423_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendstatus',
            name='user_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
