# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.CharField(default=b'29204', max_length=64),
        ),
    ]
