# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190423_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvisibility',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='postvisibility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
